name: Build Bypass rules dat files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
  push:
    branches:
      - master
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout codebase
      uses: actions/checkout@v3
      with:
          path: code

    - name: Set variables
      run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "FILE=$PWD" >> $GITHUB_ENV
          sudo timedatectl set-timezone "Asia/Shanghai"
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: https://sirpdboy:${{ secrets.REPO_TOKEN }}@github.com/

    - name: Combine
      run: |
        echo domain

        curl -fsS 5 https://raw.githubusercontent.com/pexcn/daily/gh-pages/chinalist/chinalist.txt  > ./domains_cn.txt
        echo ad
        curl -fsSL https://fastly.jsdelivr.net/gh/privacy-protection-tools/anti-AD/anti-ad-domains.txt > ./ad_list.txt
        sed -i '/^#/d' ad_list.txt
        echo ipv4
        cid="$(curl -kLfsm 5 https://ispip.clang.cn/all_cn.txt)"
        pexcnv4="$(curl -kLfsm 5 https://raw.githubusercontent.com/pexcn/daily/gh-pages/chnroute/chnroute.txt )"
        chunzhen="$(curl -kLfsm 5 https://fastly.jsdelivr.net/gh/gaoyifan/china-operator-ip@ip-lists/china.txt)"
        pdipv4="$(curl -kLfsm 5 https://raw.githubusercontent.com/sirpdboy/iplist/main/pdipv4.txt)"
        iplist="$cid\n"
        echo -e "${iplist}" | sort | uniq > all_cn.txt
        echo ipv6
        china6="$(curl -kLfsm 5 https://fastly.jsdelivr.net/gh/gaoyifan/china-operator-ip@ip-lists/china6.txt)"
        clang6="$(curl -kLfsm 5 https://ispip.clang.cn/all_cn_ipv6.txt)"
        chnroute6="$(curl -kLfsm 5 https://raw.githubusercontent.com/pexcn/daily/gh-pages/chnroute/chnroute6.txt )"
        pdipv6="$(curl -kLfsm 5 https://raw.githubusercontent.com/sirpdboy/iplist/main/pdipv6.txt)"
        iplist="$clang6\n"
        echo -e "${iplist}" | sort | uniq > all_cn_ipv6.txt 
        
        YW5="$(curl -kLfsm 5 https://fastly.jsdelivr.net/gh/YW5vbnltb3Vz/domain-list-community@release/gfwlist.txt)"
        echo $YW5 | base64 -d  | sort | uniq  > gfwlist.txt
        sed -i '/^@@|/d;/^!/d;/^#/d'  gfwlist.txt
         curl curl -fsSL https://raw.githubusercontent.com/pexcn/daily/gh-pages/gfwlist/gfwlist.txt > gfwlist.txt
        v4=`cat all_cn.txt | wc -l `
        v6=`cat all_cn_ipv6.txt  | wc -l `
        gfw=`cat gfwlist.txt | wc -l `
        ads=`cat ad_list.txt | wc -l `
        cn=`cat domains_cn.txt | wc -l `
        
          sha256sum all_cn.txt > all_cn.txt.sha256sum
          sha256sum all_cn_ipv6.txt > all_cn_ipv6.txt.sha256sum
          sha256sum gfwlist.txt > gfwlist.txt.sha256sum
          sha256sum ad_list.txt > ad_list.txt.sha256sum
          sha256sum domains_cn.txt > domains_cn.txt.sha256sum
        echo -e " Update $(date +%Y-%m-%d" "%H:%M:%S) for bypass \n domains_cn:$cn \n ipv4:$v4 \n ipv6:$v6 \n GFW:$gfw \n AD_smartdns:$ads" > README.md
        ls
        rm -rf gfwlist.tmp 
        # rm -rf chinalist.txt accelerated-domains.china.conf cn.txt common.txt accelerated-domains.china.txt cn_1.txt temp-direct.txt
 
        
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: ${{ env.FILE }}/*
          
    - name: Git push assets to "release" branch
      run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add *.txt README.md
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          retain_days: 1
          keep_minimum_runs: 1

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
          keep_latest: 1
          delete_tags: true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
         name: |
            bin-archive
